name: "Set up schema file for a run"
author: Luke Swanson
description: "Given a game to export, make a copy of its schema from the template."
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  game:
    description: "Game selected for data export"
    required: false
    default: "game"
runs:
  using: "composite"
  steps:
    - name: Set up schema file
      run: cp src/ogd/core/games/${{inputs.game}}/schemas/${{inputs.game}}.json.template games/${{inputs.game}}/schemas/${{inputs.game}}.json
      shell: bash