name: "Export Previous Week of Data"
author: Luke Swanson
description: "Given a game, this action will export last week's data for that game."
branding:
  icon: 'calendar'
  color: 'purple'
inputs:
  game:
    description: "The game with data to export."
    required: true
    default: 'AQUALAB'
  python_version:
    description: "Which version of Python to install on local GitHub Actions runner."
    required: false
    default: "3.12"

runs:
  using: "composite"
  steps:
  - name: Get last week, for export
    run: |
      LASTWEEK=$(date -d "$(date +%Y-%m-%d) -1 week" +'%m/%d/%Y')
      YESTERDAY=$(date -d "$(date +%Y-%m-%d) -1 day" +'%m/%d/%Y')
      echo "LASTWEEK=" $LASTWEEK >> $GITHUB_ENV
      echo "YESTERDAY=" $YESTERDAY >> $GITHUB_ENV
    shell: bash
  - name: Execute data export
    uses: ./.github/actions/export_custom
    with:
      game: ${{ inputs.game }}
      with_events: true
      with_features: true
      start_date: ${{ env.LASTWEEK }}
      end_date: ${{ env.YESTERDAY }}
      python_version: ${{ inputs.python_version }}
