import json

_enum_to_interactive_entry = {
  0: 'tunic.entry_voteforgramps',
  1: 'tunic.entry_tunic',
  2: 'tunic.entry_cleanerslip',
  3: 'tunic.entry_basketballplaque',
  4: 'tunic.entry_teddytaken',
  5: 'tunic.entry_javajacket',
  6: 'tunic.entry_onthecase',
  7: 'tunic.entry_archivistcoffee',
  8: 'tunic.entry_expert',
  9: 'tunic.entry_logbook',
  10: 'tunic.entry_cleanercard',
  11: 'tunic.entry_microfiche',
  12: 'tunic.entry_newspaper',
  13: 'tunic.entry_taxidermy',
  14: 'tunic.entry_wellsid',
  15: 'tunic.entry_stacks_slip',
  16: 'tunic.entry_theodora',
  17: 'tunic.entry_scratches',
  18: 'tunic.entry_glasses',
  19: 'tunic.entry_teddyfree',
  20: 'tunic.entry_teddyfound',
  21: 'tunic.entry_key',
  22: 'tunic.entry_staffdir',
  23: 'tunic.entry_flag',
  24: 'tunic.entry_wellshoof',
  25: 'tunic.entry_tracks',
  26: 'tunic.entry_littering',
  27: 'tunic.entry_flaglady',
  28: 'tunic.entry_ecologyflag',
  29: 'tunic.entry_theta',
  30: 'tunic.entry_nelson',
  31: 'tunic.entry_activists'
}


def enum_to_interactive_entry(enum):
  return _enum_to_interactive_entry.get(enum)


_interactive_entry_to_char = {v: chr(65+i+(i>25)*6) for i, v in _enum_to_interactive_entry.items()}
"""{'tunic.entry_voteforgramps': 'A',
 'tunic.entry_tunic': 'B',
 'tunic.entry_cleanerslip': 'C',
 'tunic.entry_basketballplaque': 'D',
 'tunic.entry_teddytaken': 'E',
 'tunic.entry_javajacket': 'F',
 'tunic.entry_onthecase': 'G',
 'tunic.entry_archivistcoffee': 'H',
 'tunic.entry_expert': 'I',
 'tunic.entry_logbook': 'J',
 'tunic.entry_cleanercard': 'K',
 'tunic.entry_microfiche': 'L',
 'tunic.entry_newspaper': 'M',
 'tunic.entry_taxidermy': 'N',
 'tunic.entry_wellsid': 'O',
 'tunic.entry_stacks_slip': 'P',
 'tunic.entry_theodora': 'Q',
 'tunic.entry_scratches': 'R',
 'tunic.entry_glasses': 'S',
 'tunic.entry_teddyfree': 'T',
 'tunic.entry_teddyfound': 'U',
 'tunic.entry_key': 'V',
 'tunic.entry_staffdir': 'W',
 'tunic.entry_flag': 'X',
 'tunic.entry_wellshoof': 'Y',
 'tunic.entry_tracks': 'Z',
 'tunic.entry_littering': 'a',
 'tunic.entry_flaglady': 'b',
 'tunic.entry_ecologyflag': 'c',
 'tunic.entry_theta': 'd',
 'tunic.entry_nelson': 'e',
 'tunic.entry_activists': 'f'}"""

def interactive_entry_to_char(entry_fqid):
  return _interactive_entry_to_char.get(entry_fqid) or ''


_assessment_answers = {
  1: ['tunic.entry_tunic','HACKME','tunic.entry_basketballplaque','tunic.entry_cleanerslip'],
  2: ['tunic.entry_cleanerslip','tunic.entry_expert','tunic.entry_cleanercard','tunic.entry_logbook',
     'tunic.entry_newspaper','tunic.entry_theodora'],
  3: ['tunic.entry_teddytaken','tunic.entry_javajacket','tunic.entry_archivistcoffee','tunic.entry_taxidermy'],
  4: ['tunic.entry_tracks', 'tunic.entry_ecologyflag', 'tunic.entry_theta','tunic.entry_nelson','tunic.entry_activists']
}

q_to_assessment = {
 0: 1,
 1: 1,
 2: 1,
 3: 1,
 4: 2,
 5: 2,
 6: 2,
 7: 2,
 8: 2,
 9: 2,
 10: 3,
 11: 3,
 12: 3,
 13: 3,
 14: 4,
 15: 4,
 16: 4,
 17: 4,
 18: 4
}

assessement_to_lvl = {
    1: 4,
    2: 12,
    3: 12,
    4: 22
}
assessment_to_last_q = {
    1: 3,
    2: 9,
    3: 13,
    4: 18
}



_answer_fqid_to_q_num = {
  'tunic.entry_tunic4': 0,
 'HACKME4': 1,
 'tunic.entry_basketballplaque4': 2,
 'tunic.entry_cleanerslip4': 3,
 'tunic.entry_cleanerslip12': 4,
 'tunic.entry_expert12': 5,
 'tunic.entry_cleanercard12': 6,
 'tunic.entry_logbook12': 7,
 'tunic.entry_newspaper12': 8,
 'tunic.entry_theodora12': 9,
 'tunic.entry_teddytaken12': 10,
 'tunic.entry_javajacket12': 11,
 'tunic.entry_archivistcoffee12': 12,
 'tunic.entry_taxidermy12': 13,
 'tunic.entry_tracks22': 14,
 'tunic.entry_ecologyflag22': 15,
 'tunic.entry_theta22': 16,
 'tunic.entry_nelson22': 17,
 'tunic.entry_activists22': 18
}


answer_to_question = lambda ans,lvl: _answer_fqid_to_q_num[f'{ans}{lvl}']

_answer_chars = ['B',
 None, # standin for D or C
 'D',
 'C',
 'C',
 'I',
 'K',
 'J',
 'M',
 'Q',
 'E',
 'F',
 'H',
 'N',
 'Z',
 'c',
 'd',
 'e',
 'f']

_fqid_to_enum = {'tunic.capitol_0.hall.boss.chap1_finale_0': 0,
 'tunic.capitol_0.hall.boss.chap1_finale_0_fail': 1,
 'tunic.capitol_0.hall.boss.chap1_finale_1': 2,
 'tunic.capitol_0.hall.boss.chap1_finale_1_fail': 3,
 'tunic.capitol_0.hall.boss.chap1_finale_2': 4,
 'tunic.capitol_0.hall.boss.chap1_finale_plaquefirst_0': 5,
 'tunic.capitol_0.hall.boss.chap1_finale_plaquefirst_0_fail': 6,
 'tunic.capitol_0.hall.boss.chap1_finale_plaquefirst_1': 7,
 'tunic.capitol_0.hall.boss.chap1_finale_slipfirst_0': 8,
 'tunic.capitol_0.hall.boss.chap1_finale_slipfirst_0_fail': 9,
 'tunic.capitol_0.hall.boss.chap1_finale_slipfirst_1': 10,
 'tunic.capitol_0.hall.boss.talktogramps': 11,
 'tunic.capitol_0.hall.chap1_finale_c': 12,
 'tunic.capitol_0.hall.gramps.hub': 13,
 'tunic.capitol_1.hall.boss.chap2_finale_0': 14,
 'tunic.capitol_1.hall.boss.chap2_finale_0_fail': 15,
 'tunic.capitol_1.hall.boss.chap2_finale_1': 16,
 'tunic.capitol_1.hall.boss.chap2_finale_1_fail': 17,
 'tunic.capitol_1.hall.boss.chap2_finale_2': 18,
 'tunic.capitol_1.hall.boss.chap2_finale_2_fail': 19,
 'tunic.capitol_1.hall.boss.chap2_finale_3': 20,
 'tunic.capitol_1.hall.boss.chap2_finale_3_fail': 21,
 'tunic.capitol_1.hall.boss.chap2_finale_4': 22,
 'tunic.capitol_1.hall.boss.chap2_finale_4_fail': 23,
 'tunic.capitol_1.hall.boss.chap2_finale_5': 24,
 'tunic.capitol_1.hall.boss.chap2_finale_5_fail': 25,
 'tunic.capitol_1.hall.boss.chap2_finale_6': 26,
 'tunic.capitol_1.hall.boss.chap2_finale_6_fail': 27,
 'tunic.capitol_1.hall.boss.chap2_teddy_finale_1': 28,
 'tunic.capitol_1.hall.boss.chap2_teddy_finale_1_fail': 29,
 'tunic.capitol_1.hall.boss.haveyougotit': 30,
 'tunic.capitol_1.hall.boss.writeitup': 31,
 'tunic.capitol_1.hall.chap2_finale_c': 32,
 'tunic.capitol_1.hall.gramps.chap2_teddy_finale_0': 33,
 'tunic.capitol_1.hall.gramps.chap2_teddy_finale_0_fail': 34,
 'tunic.capitol_1.hall.gramps.chap2_teddy_finale_2': 35,
 'tunic.capitol_1.hall.gramps.chap2_teddy_finale_2_fail': 36,
 'tunic.capitol_1.hall.gramps.chap2_teddy_finale_4': 37,
 'tunic.capitol_1.hall.gramps.chap2_teddy_finale_4_fail': 38,
 'tunic.capitol_1.hall.wells.chap2_teddy_finale_3': 39,
 'tunic.capitol_1.hall.wells.chap2_teddy_finale_3_fail': 40,
 'tunic.capitol_1.hall.wells.hub': 41,
 'tunic.capitol_2.hall.boss.chap4_finale_0': 42,
 'tunic.capitol_2.hall.boss.chap4_finale_0_fail': 43,
 'tunic.capitol_2.hall.boss.chap4_finale_1': 44,
 'tunic.capitol_2.hall.boss.chap4_finale_1_fail': 45,
 'tunic.capitol_2.hall.boss.chap4_finale_2': 46,
 'tunic.capitol_2.hall.boss.chap4_finale_2_fail': 47,
 'tunic.capitol_2.hall.boss.chap4_finale_3': 48,
 'tunic.capitol_2.hall.boss.chap4_finale_3_fail': 49,
 'tunic.capitol_2.hall.boss.chap4_finale_4': 50,
 'tunic.capitol_2.hall.boss.chap4_finale_4_fail': 51,
 'tunic.capitol_2.hall.boss.chap4_finale_5': 52,
 'tunic.capitol_2.hall.boss.chap4_finale_5_fail': 53,
 'tunic.capitol_2.hall.boss.haveyougotit': 54,
 'tunic.capitol_2.hall.chap4_finale_c': 55,
 'tunic.capitol_3.hall.chap5_finale_c': 56,
 'tunic.capitol_3.hall.crowd.hub': 57,
 'tunic.capitol_3.hall.gramps.hub': 58,
 'tunic.capitol_3.hall.teddy.speak': 59,
 'tunic.drycleaner.frontdesk.block_0': 60,
 'tunic.drycleaner.frontdesk.block_1': 61,
 'tunic.drycleaner.frontdesk.logbook': 62,
 'tunic.drycleaner.frontdesk.logbook.page.bingo': 63,
 'tunic.drycleaner.frontdesk.worker.done': 64,
 'tunic.drycleaner.frontdesk.worker.done2': 65,
 'tunic.drycleaner.frontdesk.worker.hub': 66,
 'tunic.drycleaner.frontdesk.worker.takealook': 67,
 'tunic.flaghouse.entry.colorbook': 68,
 'tunic.flaghouse.entry.flag_girl.hello': 69,
 'tunic.flaghouse.entry.flag_girl.hello_recap': 70,
 'tunic.flaghouse.entry.flag_girl.symbol': 71,
 'tunic.flaghouse.entry.flag_girl.symbol_recap': 72,
 'tunic.historicalsociety.basement.ch3start': 73,
 'tunic.historicalsociety.basement.gramps.seeyalater': 74,
 'tunic.historicalsociety.basement.gramps.whatdo': 75,
 'tunic.historicalsociety.basement.janitor': 76,
 'tunic.historicalsociety.basement.savedteddy': 77,
 'tunic.historicalsociety.basement.seescratches': 78,
 'tunic.historicalsociety.cage.confrontation': 79,
 'tunic.historicalsociety.cage.glasses.afterteddy': 80,
 'tunic.historicalsociety.cage.glasses.beforeteddy': 81,
 'tunic.historicalsociety.cage.lockeddoor': 82,
 'tunic.historicalsociety.cage.need_glasses': 83,
 'tunic.historicalsociety.cage.teddy.trapped': 84,
 'tunic.historicalsociety.cage.unlockdoor': 85,
 'tunic.historicalsociety.closet.doorblock': 86,
 'tunic.historicalsociety.closet.gramps.intro_0_cs_0': 87,
 'tunic.historicalsociety.closet.notebook': 88,
 'tunic.historicalsociety.closet.photo': 89,
 'tunic.historicalsociety.closet.retirement_letter.hub': 90,
 'tunic.historicalsociety.closet.teddy.intro_0_cs_0': 91,
 'tunic.historicalsociety.closet.teddy.intro_0_cs_5': 92,
 'tunic.historicalsociety.closet_dirty.door_block_clean': 93,
 'tunic.historicalsociety.closet_dirty.door_block_talk': 94,
 'tunic.historicalsociety.closet_dirty.gramps.archivist': 95,
 'tunic.historicalsociety.closet_dirty.gramps.helpclean': 96,
 'tunic.historicalsociety.closet_dirty.gramps.news': 97,
 'tunic.historicalsociety.closet_dirty.gramps.nothing': 98,
 'tunic.historicalsociety.closet_dirty.photo': 99,
 'tunic.historicalsociety.closet_dirty.trigger_coffee': 100,
 'tunic.historicalsociety.closet_dirty.trigger_scarf': 101,
 'tunic.historicalsociety.closet_dirty.what_happened': 102,
 'tunic.historicalsociety.collection': 103,
 'tunic.historicalsociety.collection.cs': 104,
 'tunic.historicalsociety.collection.gramps.found': 105,
 'tunic.historicalsociety.collection.gramps.look_0': 106,
 'tunic.historicalsociety.collection.gramps.lost': 107,
 'tunic.historicalsociety.collection.slip': 108,
 'tunic.historicalsociety.collection_flag.gramps.flag': 109,
 'tunic.historicalsociety.collection_flag.gramps.recap': 110,
 'tunic.historicalsociety.entry.block_tocollection': 111,
 'tunic.historicalsociety.entry.block_tomap1': 112,
 'tunic.historicalsociety.entry.block_tomap2': 113,
 'tunic.historicalsociety.entry.boss.flag': 114,
 'tunic.historicalsociety.entry.boss.flag_recap': 115,
 'tunic.historicalsociety.entry.boss.talktogramps': 116,
 'tunic.historicalsociety.entry.directory.closeup.archivist': 117,
 'tunic.historicalsociety.entry.gramps.hub': 118,
 'tunic.historicalsociety.entry.groupconvo': 119,
 'tunic.historicalsociety.entry.groupconvo_flag': 120,
 'tunic.historicalsociety.entry.wells.flag': 121,
 'tunic.historicalsociety.entry.wells.flag_recap': 122,
 'tunic.historicalsociety.entry.wells.talktogramps': 123,
 'tunic.historicalsociety.frontdesk.archivist.foundtheodora': 124,
 'tunic.historicalsociety.frontdesk.archivist.have_glass': 125,
 'tunic.historicalsociety.frontdesk.archivist.have_glass_recap': 126,
 'tunic.historicalsociety.frontdesk.archivist.hello': 127,
 'tunic.historicalsociety.frontdesk.archivist.need_glass_0': 128,
 'tunic.historicalsociety.frontdesk.archivist.need_glass_1': 129,
 'tunic.historicalsociety.frontdesk.archivist.newspaper': 130,
 'tunic.historicalsociety.frontdesk.archivist.newspaper_recap': 131,
 'tunic.historicalsociety.frontdesk.archivist_glasses.confrontation': 132,
 'tunic.historicalsociety.frontdesk.archivist_glasses.confrontation_recap': 133,
 'tunic.historicalsociety.frontdesk.block_magnify': 134,
 'tunic.historicalsociety.frontdesk.key': 135,
 'tunic.historicalsociety.frontdesk.magnify': 136,
 'tunic.historicalsociety.stacks.block': 137,
 'tunic.historicalsociety.stacks.journals': 138,
 'tunic.historicalsociety.stacks.journals.pic_2.bingo': 139,
 'tunic.historicalsociety.stacks.journals_flag': 140,
 'tunic.historicalsociety.stacks.journals_flag.pic_0.bingo': 141,
 'tunic.historicalsociety.stacks.journals_flag.pic_1.bingo': 142,
 'tunic.historicalsociety.stacks.journals_flag.pic_2.bingo': 143,
 'tunic.historicalsociety.stacks.outtolunch': 144,
 'tunic.humanecology.frontdesk.block_0': 145,
 'tunic.humanecology.frontdesk.block_1': 146,
 'tunic.humanecology.frontdesk.businesscards': 147,
 'tunic.humanecology.frontdesk.businesscards.card_bingo.bingo': 148,
 'tunic.humanecology.frontdesk.worker.badger': 149,
 'tunic.humanecology.frontdesk.worker.intro': 150,
 'tunic.kohlcenter.halloffame.block_0': 151,
 'tunic.kohlcenter.halloffame.block_1': 152,
 'tunic.kohlcenter.halloffame.plaque.face': 153,
 'tunic.kohlcenter.halloffame.plaque.face.date': 154,
 'tunic.kohlcenter.halloffame.togrampa': 155,
 'tunic.library.frontdesk.block_badge': 156,
 'tunic.library.frontdesk.block_badge_2': 157,
 'tunic.library.frontdesk.block_nelson': 158,
 'tunic.library.frontdesk.wellsbadge.hub': 159,
 'tunic.library.frontdesk.worker.droppedbadge': 160,
 'tunic.library.frontdesk.worker.flag': 161,
 'tunic.library.frontdesk.worker.flag_recap': 162,
 'tunic.library.frontdesk.worker.hello': 163,
 'tunic.library.frontdesk.worker.hello_short': 164,
 'tunic.library.frontdesk.worker.nelson': 165,
 'tunic.library.frontdesk.worker.nelson_recap': 166,
 'tunic.library.frontdesk.worker.preflag': 167,
 'tunic.library.frontdesk.worker.wells': 168,
 'tunic.library.frontdesk.worker.wells_recap': 169,
 'tunic.library.microfiche.block_0': 170,
 'tunic.library.microfiche.reader': 171,
 'tunic.library.microfiche.reader.paper2.bingo': 172,
 'tunic.library.microfiche.reader_flag.paper2.bingo': 173,
 'tunic.nelson.trail.coffee': 174,
 'tunic.nelson.trail.conclusion': 175,
 'tunic.nelson.trail.display': 176,
 'tunic.nelson.trail.gramps.question': 177,
 'tunic.wildlife.center.coffee': 178,
 'tunic.wildlife.center.crane_ranger.crane': 179,
 'tunic.wildlife.center.expert.recap': 180,
 'tunic.wildlife.center.expert.removed_cup': 181,
 'tunic.wildlife.center.fox.concern': 182,
 'tunic.wildlife.center.remove_cup': 183,
 'tunic.wildlife.center.tracks.hub.deer': 184,
 'tunic.wildlife.center.wells.animals': 185,
 'tunic.wildlife.center.wells.animals2': 186,
 'tunic.wildlife.center.wells.nodeer': 187,
 'tunic.wildlife.center.wells.nodeer_recap': 188}

