import json

_enum_to_interactive_entry = {
  0: 'tunic.entry_voteforgramps',
  1: 'tunic.entry_tunic',
  2: 'tunic.entry_cleanerslip',
  3: 'tunic.entry_basketballplaque',
  4: 'tunic.entry_teddytaken',
  5: 'tunic.entry_javajacket',
  6: 'tunic.entry_onthecase',
  7: 'tunic.entry_archivistcoffee',
  8: 'tunic.entry_expert',
  9: 'tunic.entry_logbook',
  10: 'tunic.entry_cleanercard',
  11: 'tunic.entry_microfiche',
  12: 'tunic.entry_newspaper',
  13: 'tunic.entry_taxidermy',
  14: 'tunic.entry_wellsid',
  15: 'tunic.entry_stacks_slip',
  16: 'tunic.entry_theodora',
  17: 'tunic.entry_scratches',
  18: 'tunic.entry_glasses',
  19: 'tunic.entry_teddyfree',
  20: 'tunic.entry_teddyfound',
  21: 'tunic.entry_key',
  22: 'tunic.entry_staffdir',
  23: 'tunic.entry_flag',
  24: 'tunic.entry_wellshoof',
  25: 'tunic.entry_tracks',
  26: 'tunic.entry_littering',
  27: 'tunic.entry_flaglady',
  28: 'tunic.entry_ecologyflag',
  29: 'tunic.entry_theta',
  30: 'tunic.entry_nelson',
  31: 'tunic.entry_activists'
}


def enum_to_interactive_entry(enum):
  return _enum_to_interactive_entry.get(enum)


_interactive_entry_to_char = {v: chr(65+i+(i>25)*6) for i, v in _enum_to_interactive_entry.items()}
"""{'tunic.entry_voteforgramps': 'A',
 'tunic.entry_tunic': 'B',
 'tunic.entry_cleanerslip': 'C',
 'tunic.entry_basketballplaque': 'D',
 'tunic.entry_teddytaken': 'E',
 'tunic.entry_javajacket': 'F',
 'tunic.entry_onthecase': 'G',
 'tunic.entry_archivistcoffee': 'H',
 'tunic.entry_expert': 'I',
 'tunic.entry_logbook': 'J',
 'tunic.entry_cleanercard': 'K',
 'tunic.entry_microfiche': 'L',
 'tunic.entry_newspaper': 'M',
 'tunic.entry_taxidermy': 'N',
 'tunic.entry_wellsid': 'O',
 'tunic.entry_stacks_slip': 'P',
 'tunic.entry_theodora': 'Q',
 'tunic.entry_scratches': 'R',
 'tunic.entry_glasses': 'S',
 'tunic.entry_teddyfree': 'T',
 'tunic.entry_teddyfound': 'U',
 'tunic.entry_key': 'V',
 'tunic.entry_staffdir': 'W',
 'tunic.entry_flag': 'X',
 'tunic.entry_wellshoof': 'Y',
 'tunic.entry_tracks': 'Z',
 'tunic.entry_littering': 'a',
 'tunic.entry_flaglady': 'b',
 'tunic.entry_ecologyflag': 'c',
 'tunic.entry_theta': 'd',
 'tunic.entry_nelson': 'e',
 'tunic.entry_activists': 'f'}"""

def interactive_entry_to_char(entry_fqid):
  return _interactive_entry_to_char.get(entry_fqid) or ''


_assessment_answers = {
  1: ['tunic.entry_tunic','HACKME','tunic.entry_basketballplaque','tunic.entry_cleanerslip'],
  2: ['tunic.entry_cleanerslip','tunic.entry_expert','tunic.entry_cleanercard','tunic.entry_logbook',
     'tunic.entry_newspaper','tunic.entry_theodora'],
  3: ['tunic.entry_teddytaken','tunic.entry_javajacket','tunic.entry_archivistcoffee','tunic.entry_taxidermy'],
  4: ['tunic.entry_tracks', 'tunic.entry_ecologyflag', 'tunic.entry_theta','tunic.entry_nelson','tunic.entry_activists']
}

q_to_assessment = {
 0: 1,
 1: 1,
 2: 1,
 3: 1,
 4: 2,
 5: 2,
 6: 2,
 7: 2,
 8: 2,
 9: 2,
 10: 3,
 11: 3,
 12: 3,
 13: 3,
 14: 4,
 15: 4,
 16: 4,
 17: 4,
 18: 4
}

assessement_to_lvl = {
    1: 4,
    2: 12,
    3: 12,
    4: 22
}
assessment_to_last_q = {
    1: 3,
    2: 9,
    3: 13,
    4: 18
}



_answer_fqid_to_q_num = {
  'tunic.entry_tunic4': 0,
 'HACKME4': 1,
 'tunic.entry_basketballplaque4': 2,
 'tunic.entry_cleanerslip4': 3,
 'tunic.entry_cleanerslip12': 4,
 'tunic.entry_expert12': 5,
 'tunic.entry_cleanercard12': 6,
 'tunic.entry_logbook12': 7,
 'tunic.entry_newspaper12': 8,
 'tunic.entry_theodora12': 9,
 'tunic.entry_teddytaken12': 10,
 'tunic.entry_javajacket12': 11,
 'tunic.entry_archivistcoffee12': 12,
 'tunic.entry_taxidermy12': 13,
 'tunic.entry_tracks22': 14,
 'tunic.entry_ecologyflag22': 15,
 'tunic.entry_theta22': 16,
 'tunic.entry_nelson22': 17,
 'tunic.entry_activists22': 18
}


answer_to_question = lambda ans,lvl: _answer_fqid_to_q_num[f'{ans}{lvl}']

_answer_chars = ['B',
 None, # standin for D or C
 'D',
 'C',
 'C',
 'I',
 'K',
 'J',
 'M',
 'Q',
 'E',
 'F',
 'H',
 'N',
 'Z',
 'c',
 'd',
 'e',
 'f']

fqid_to_enum = {'tunic.historicalsociety.closet.teddy.intro_0_cs_0': 0,
'tunic.historicalsociety.closet.teddy.intro_0_cs_5': 1,
'tunic.historicalsociety.closet.doorblock': 2,
'tunic.historicalsociety.closet.gramps.intro_0_cs_0': 3,
'tunic.historicalsociety.closet.notebook': 4,
'tunic.historicalsociety.closet.photo': 5,
'tunic.historicalsociety.closet.retirement_letter.hub': 6,
'tunic.historicalsociety.basement.ch3start': 7,
'tunic.historicalsociety.basement.gramps.seeyalater': 8,
'tunic.historicalsociety.basement.gramps.whatdo': 9,
'tunic.historicalsociety.basement.janitor': 10,
'tunic.historicalsociety.basement.savedteddy': 11,
'tunic.historicalsociety.basement.seescratches': 12,
'tunic.historicalsociety.entry.block_tocollection': 13,
'tunic.historicalsociety.entry.block_tomap1': 14,
'tunic.historicalsociety.entry.block_tomap2': 15,
'tunic.historicalsociety.entry.boss.flag': 16,
'tunic.historicalsociety.entry.boss.flag_recap': 17,
'tunic.historicalsociety.entry.boss.talktogramps': 18,
'tunic.historicalsociety.entry.directory.closeup.archivist': 19,
'tunic.historicalsociety.entry.gramps.hub': 20,
'tunic.historicalsociety.entry.groupconvo': 21,
'tunic.historicalsociety.entry.groupconvo_flag': 22,
'tunic.historicalsociety.entry.wells.flag': 23,
'tunic.historicalsociety.entry.wells.flag_recap': 24,
'tunic.historicalsociety.entry.wells.talktogramps': 25,
'tunic.historicalsociety.collection': 26,
'tunic.historicalsociety.collection.cs': 27,
'tunic.historicalsociety.collection.gramps.found': 28,
'tunic.historicalsociety.collection.gramps.look_0': 29,
'tunic.historicalsociety.collection.gramps.lost': 30,
'tunic.historicalsociety.collection.slip': 31,
'tunic.kohlcenter.halloffame.block_0': 32,
'tunic.kohlcenter.halloffame.block_1': 33,
'tunic.kohlcenter.halloffame.plaque.face': 34,
'tunic.kohlcenter.halloffame.plaque.face.date': 35,
'tunic.kohlcenter.halloffame.togrampa': 36,
'tunic.capitol_0.hall.boss.chap1_finale_0': 37,
'tunic.capitol_0.hall.boss.chap1_finale_0_fail': 38,
'tunic.capitol_0.hall.boss.chap1_finale_1': 39,
'tunic.capitol_0.hall.boss.chap1_finale_1_fail': 40,
'tunic.capitol_0.hall.boss.chap1_finale_2': 41,
'tunic.capitol_0.hall.boss.chap1_finale_plaquefirst_0': 42,
'tunic.capitol_0.hall.boss.chap1_finale_plaquefirst_0_fail': 43,
'tunic.capitol_0.hall.boss.chap1_finale_plaquefirst_1': 44,
'tunic.capitol_0.hall.boss.chap1_finale_slipfirst_0': 45,
'tunic.capitol_0.hall.boss.chap1_finale_slipfirst_0_fail': 46,
'tunic.capitol_0.hall.boss.chap1_finale_slipfirst_1': 47,
'tunic.capitol_0.hall.boss.talktogramps': 48,
'tunic.capitol_0.hall.chap1_finale_c': 49,
'tunic.capitol_0.hall.gramps.hub': 50,
'tunic.historicalsociety.closet_dirty.door_block_clean': 51,
'tunic.historicalsociety.closet_dirty.door_block_talk': 52,
'tunic.historicalsociety.closet_dirty.gramps.archivist': 53,
'tunic.historicalsociety.closet_dirty.gramps.helpclean': 54,
'tunic.historicalsociety.closet_dirty.gramps.news': 55,
'tunic.historicalsociety.closet_dirty.gramps.nothing': 56,
'tunic.historicalsociety.closet_dirty.photo': 57,
'tunic.historicalsociety.closet_dirty.trigger_coffee': 58,
'tunic.historicalsociety.closet_dirty.trigger_scarf': 59,
'tunic.historicalsociety.closet_dirty.what_happened': 60,
'tunic.historicalsociety.stacks.block': 61,
'tunic.historicalsociety.stacks.journals': 62,
'tunic.historicalsociety.stacks.journals.pic_2.bingo': 63,
'tunic.historicalsociety.stacks.journals_flag': 64,
'tunic.historicalsociety.stacks.journals_flag.pic_0.bingo': 65,
'tunic.historicalsociety.stacks.journals_flag.pic_1.bingo': 66,
'tunic.historicalsociety.stacks.journals_flag.pic_2.bingo': 67,
'tunic.historicalsociety.stacks.outtolunch': 68,
'tunic.historicalsociety.frontdesk.archivist.foundtheodora': 69,
'tunic.historicalsociety.frontdesk.archivist.have_glass': 70,
'tunic.historicalsociety.frontdesk.archivist.have_glass_recap': 71,
'tunic.historicalsociety.frontdesk.archivist.hello': 72,
'tunic.historicalsociety.frontdesk.archivist.need_glass_0': 73,
'tunic.historicalsociety.frontdesk.archivist.need_glass_1': 74,
'tunic.historicalsociety.frontdesk.archivist.newspaper': 75,
'tunic.historicalsociety.frontdesk.archivist.newspaper_recap': 76,
'tunic.historicalsociety.frontdesk.archivist_glasses.confrontation': 77,
'tunic.historicalsociety.frontdesk.archivist_glasses.confrontation_recap': 78,
'tunic.historicalsociety.frontdesk.block_magnify': 79,
'tunic.historicalsociety.frontdesk.key': 80,
'tunic.historicalsociety.frontdesk.magnify': 81,
'tunic.humanecology.frontdesk.block_0': 82,
'tunic.humanecology.frontdesk.block_1': 83,
'tunic.humanecology.frontdesk.businesscards': 84,
'tunic.humanecology.frontdesk.businesscards.card_bingo.bingo': 85,
'tunic.humanecology.frontdesk.worker.badger': 86,
'tunic.humanecology.frontdesk.worker.intro': 87,
'tunic.drycleaner.frontdesk.block_0': 88,
'tunic.drycleaner.frontdesk.block_1': 89,
'tunic.drycleaner.frontdesk.logbook': 90,
'tunic.drycleaner.frontdesk.logbook.page.bingo': 91,
'tunic.drycleaner.frontdesk.worker.done': 92,
'tunic.drycleaner.frontdesk.worker.done2': 93,
'tunic.drycleaner.frontdesk.worker.hub': 94,
'tunic.drycleaner.frontdesk.worker.takealook': 95,
'tunic.library.frontdesk.block_badge': 96,
'tunic.library.frontdesk.block_badge_2': 97,
'tunic.library.frontdesk.block_nelson': 98,
'tunic.library.frontdesk.wellsbadge.hub': 99,
'tunic.library.frontdesk.worker.droppedbadge': 100,
'tunic.library.frontdesk.worker.flag': 101,
'tunic.library.frontdesk.worker.flag_recap': 102,
'tunic.library.frontdesk.worker.hello': 103,
'tunic.library.frontdesk.worker.hello_short': 104,
'tunic.library.frontdesk.worker.nelson': 105,
'tunic.library.frontdesk.worker.nelson_recap': 106,
'tunic.library.frontdesk.worker.preflag': 107,
'tunic.library.frontdesk.worker.wells': 108,
'tunic.library.frontdesk.worker.wells_recap': 109,
'tunic.library.microfiche.block_0': 110,
'tunic.library.microfiche.reader': 111,
'tunic.library.microfiche.reader.paper2.bingo': 112,
'tunic.library.microfiche.reader_flag.paper2.bingo': 113,
'tunic.capitol_1.hall.boss.chap2_finale_0': 114,
'tunic.capitol_1.hall.boss.chap2_finale_0_fail': 115,
'tunic.capitol_1.hall.boss.chap2_finale_1': 116,
'tunic.capitol_1.hall.boss.chap2_finale_1_fail': 117,
'tunic.capitol_1.hall.boss.chap2_finale_2': 118,
'tunic.capitol_1.hall.boss.chap2_finale_2_fail': 119,
'tunic.capitol_1.hall.boss.chap2_finale_3': 120,
'tunic.capitol_1.hall.boss.chap2_finale_3_fail': 121,
'tunic.capitol_1.hall.boss.chap2_finale_4': 122,
'tunic.capitol_1.hall.boss.chap2_finale_4_fail': 123,
'tunic.capitol_1.hall.boss.chap2_finale_5': 124,
'tunic.capitol_1.hall.boss.chap2_finale_5_fail': 125,
'tunic.capitol_1.hall.boss.chap2_finale_6': 126,
'tunic.capitol_1.hall.boss.chap2_finale_6_fail': 127,
'tunic.capitol_1.hall.boss.chap2_teddy_finale_1': 128,
'tunic.capitol_1.hall.boss.chap2_teddy_finale_1_fail': 129,
'tunic.capitol_1.hall.boss.haveyougotit': 130,
'tunic.capitol_1.hall.boss.writeitup': 131,
'tunic.capitol_1.hall.chap2_finale_c': 132,
'tunic.capitol_1.hall.gramps.chap2_teddy_finale_0': 133,
'tunic.capitol_1.hall.gramps.chap2_teddy_finale_0_fail': 134,
'tunic.capitol_1.hall.gramps.chap2_teddy_finale_2': 135,
'tunic.capitol_1.hall.gramps.chap2_teddy_finale_2_fail': 136,
'tunic.capitol_1.hall.gramps.chap2_teddy_finale_4': 137,
'tunic.capitol_1.hall.gramps.chap2_teddy_finale_4_fail': 138,
'tunic.capitol_1.hall.wells.chap2_teddy_finale_3': 139,
'tunic.capitol_1.hall.wells.chap2_teddy_finale_3_fail': 140,
'tunic.capitol_1.hall.wells.hub': 141,
'tunic.historicalsociety.cage.confrontation': 142,
'tunic.historicalsociety.cage.glasses.afterteddy': 143,
'tunic.historicalsociety.cage.glasses.beforeteddy': 144,
'tunic.historicalsociety.cage.lockeddoor': 145,
'tunic.historicalsociety.cage.need_glasses': 146,
'tunic.historicalsociety.cage.teddy.trapped': 147,
'tunic.historicalsociety.cage.unlockdoor': 148,
'tunic.historicalsociety.collection_flag.gramps.flag': 149,
'tunic.historicalsociety.collection_flag.gramps.recap': 150,
'tunic.wildlife.center.coffee': 151,
'tunic.wildlife.center.crane_ranger.crane': 152,
'tunic.wildlife.center.expert.recap': 153,
'tunic.wildlife.center.expert.removed_cup': 154,
'tunic.wildlife.center.fox.concern': 155,
'tunic.wildlife.center.remove_cup': 156,
'tunic.wildlife.center.tracks.hub.deer': 157,
'tunic.wildlife.center.wells.animals': 158,
'tunic.wildlife.center.wells.animals2': 159,
'tunic.wildlife.center.wells.nodeer': 160,
'tunic.wildlife.center.wells.nodeer_recap': 161,
'tunic.flaghouse.entry.colorbook': 162,
'tunic.flaghouse.entry.flag_girl.hello': 163,
'tunic.flaghouse.entry.flag_girl.hello_recap': 164,
'tunic.flaghouse.entry.flag_girl.symbol': 165,
'tunic.flaghouse.entry.flag_girl.symbol_recap': 166,
'tunic.capitol_2.hall.boss.chap4_finale_0': 167,
'tunic.capitol_2.hall.boss.chap4_finale_0_fail': 168,
'tunic.capitol_2.hall.boss.chap4_finale_1': 169,
'tunic.capitol_2.hall.boss.chap4_finale_1_fail': 170,
'tunic.capitol_2.hall.boss.chap4_finale_2': 171,
'tunic.capitol_2.hall.boss.chap4_finale_2_fail': 172,
'tunic.capitol_2.hall.boss.chap4_finale_3': 173,
'tunic.capitol_2.hall.boss.chap4_finale_3_fail': 174,
'tunic.capitol_2.hall.boss.chap4_finale_4': 175,
'tunic.capitol_2.hall.boss.chap4_finale_4_fail': 176,
'tunic.capitol_2.hall.boss.chap4_finale_5': 177,
'tunic.capitol_2.hall.boss.chap4_finale_5_fail': 178,
'tunic.capitol_2.hall.boss.haveyougotit': 179,
'tunic.capitol_2.hall.chap4_finale_c': 180,
'tunic.nelson.trail.coffee': 181,
'tunic.nelson.trail.conclusion': 182,
'tunic.nelson.trail.display': 183,
'tunic.nelson.trail.gramps.question': 184,
'tunic.capitol_3.hall.chap5_finale_c': 185,
'tunic.capitol_3.hall.crowd.hub': 186,
'tunic.capitol_3.hall.gramps.hub': 187,
'tunic.capitol_3.hall.teddy.speak': 188}

