name: "Export Custom Data Range"
author: Luke Swanson
description: "Given a game, this action will export last month's data for that game."
branding:
  icon: 'arrow-right'
  color: 'purple'
inputs:
  game:
   description: "The game with data to export."
   required: true
   default: 'Crystal'
  start_date:
    description: "The start date for the export"
    required: true
    default: "01/01/2021"
  end_date:
    description: "The end date for the export"
    required: true
    default: "01/01/2021"
  events_only:
    description: "If true, only export event data."
    required: false
    default: false
runs:
  using: "composite"
  steps:
    # Runs a single command using the runners shell
    # - name: Ensure we have mysql client installed.
    #   run: sudo apt-get install mysql-client
      # shell: bash
    # - name: Clone code
    #   uses: actions/checkout@v2
    - name: Execute data export
      if: ${{ ! inputs.events_only }}
      run: python3.8 main.py export ${{ inputs.game }} ${{ inputs.start_date }} ${{ inputs.end_date }}
      shell: bash
    - name: Execute data export (events only)
      if: ${{ inputs.events_only }}
      run: python3.8 main.py export ${{ inputs.game }} ${{ inputs.month_year }} --monthly --no_session_file --no_player_file --no_pop_file
      shell: bash
      # python3.8 main.py export ${{ inputs.game }} 1/1/2021 1/2/2021
