name: "Set up config file for a run"
author: Luke Swanson
description: "Given a set of appropriate inputs, this action prepares a config.py file for a data export."
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  vpn_user:
    description: "Username for logging in to the VPN."
    required: true
    default: 'user placeholder'
  vpn_pass:
    description: "Password for logging in to the VPN."
    required: true
    default: 'password placeholder'
  sql_host:
    description: "The server hosting the OGD database."
    required: true
    default: '127.0.0.1'
  sql_user:
    description: "Username for logging in to the SQL database."
    required: true
    default: 'user placeholder'
  sql_pass:
    description: "Password for logging in to the SQL database."
    required: true
    default: 'password placeholder'
  sql_db:
    description: "Which SQL database to use"
    required: true
    default: "logger"
  slice_size:
    description: "Number of sessions to process at a time"
    required: true
    default: 1000
  log_level:
    description: "Logging level to use for export process"
    required: true
    default: "INFO"
  game:
    description: "Game selected for data export"
    required: false
    default: "game"
runs:
  using: "composite"
  steps:
    - name: Set up schema file
      run: cp games/${{inputs.game}}/${{inputs.game}}.json.template games/${{inputs.game}}/${{inputs.game}}.json
      shell: bash
    - name: Set up config
      run: cp config/config.py.template config/config.py 
      shell: bash
    - name: Set SSH hostname
      run: sed -i 's/hostname/${{inputs.sql_host}}/g' config/config.py
      shell: bash
    - name: Set SSH username
      run: sed -i 's/WCER AD User/${{inputs.vpn_user}}/g' config/config.py
      shell: bash
    - name: Set SSH password
      run: sed -i 's/WCER AD Password/${{inputs.vpn_pass}}/g' config/config.py
      shell: bash
    - name: Set SQL username
      run: sed -i 's/username/${{inputs.sql_user}}/g' config/config.py
      shell: bash
    - name: Set SQL password
      run: sed -i 's/password/${{inputs.sql_pass}}/g' config/config.py
      shell: bash
    - name: Set SQL database
      run: sed -i 's/logger/${{inputs.sql_db}}/g' config/config.py
      shell: bash
    - name: Set Logger level
      run: sed -i 's/INFO/${{inputs.log_level}}/g' config/config.py
      shell: bash
    - name: Set Slice Size
      run: sed -i 's/"BATCH_SIZE":1000/"BATCH_SIZE":${{inputs.slice_size}}/g' config/config.py
      shell: bash