name: Jo Wilder Exporter CI Script
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}

on:
  push:
    paths:
    - 'src/ogd/core/generators/**'
    - 'src/ogd/games/JOWILDER/**'
    - '.github/workflows/CI_jowilder.yml'
    - '.github/actions/export_yesterday/**'
  workflow_dispatch:

jobs:
  ci_export:
    name: CI Export of Jo Wilder Data
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true

    steps:

  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get Dependencies
      uses: opengamedata/actions-setup-ogd-py-dependencies@v1.2
      with:
        python_version: ${{ vars.OGD_PYTHON_VERSION }}

  # 2. Configure cloud & local environments
    - name: Set up Google Cloud
      uses: ./.github/actions/gCloud_setup
      with:
        game: ${{ matrix.game }}
        ogd_id:  ${{ secrets.OGD_BQ_PROJECT_ID }}
        ogd_key: ${{ secrets.OGD_SELECTOR_BQ_KEY }}
        mashopolis_id:  ${{ secrets.BQ_MASHOPOLIS_PROJECT_ID }}
        mashopolis_key: ${{ secrets.BQ_MASHOPOLIS_JSON }}
        shadowspect_id:  ${{ secrets.BQ_SHADOWSPECT_PROJECT_ID }}
        shadowspect_key: ${{ secrets.BQ_SHADOWSPECT_JSON }}
        shipwrecks_id:  ${{ secrets.BQ_SHIPWRECKS_PROJECT_ID }}
        shipwrecks_key: ${{ secrets.BQ_SHIPWRECKS_JSON }}
    - name: Get Dependencies
      uses: opengamedata/actions-setup-ogd-py-dependencies@v1.2
      with:
        python_version: ${{ vars.OGD_PYTHON_VERSION }}
    - name: Set up Config File
      uses: ./.github/actions/OGD_config
      with:
        ssh_user: ${{secrets.VPN_USER}}
        ssh_pass: ${{secrets.VPN_PASS}}
        ssh_host: ${{vars.FD_LOGGER_HOST}}
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
        # TODO: set log_level to DEBUG once we've made sure there aren't excess outputs from the extractor itself.
        log_level: "INFO"

  # 3. Perform export
    - name: Do Export of yesterday's data
      uses: ./.github/actions/export_yesterday
      with:
        game: JOWILDER
        python_version: ${{ vars.OGD_PYTHON_VERSION }}

  # 4. Cleanup & complete
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: export-logs
        path: ./*.log
    - name: Upload zips as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jowilder-data
        path: ./data/JOWILDER/*.zip
