name: Penguins Exporter CI Script
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}

on:
  push:
    paths:
    - 'src/ogd/games/PENGUINS/**'
    - '.github/workflows/CI_penguins.yml'
    - '.github/actions/export_last_week/**'
  workflow_dispatch:

jobs:
  ci_export:
    name: CI Export of Penguins (Waddle) Data
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true

    steps:

  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Get Dependencies
      uses: ./.github/actions/OGD_dependencies

  # 2. Configure cloud & local environments
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.OGD_BQ_PROJECT_ID }}
        service_account_key: ${{ secrets.OGD_SELECTOR_BQ_KEY }}
        export_default_credentials: true
    - name: Set up Config File
      uses: ./.github/actions/OGD_config
      with:
        vpn_user: ${{secrets.VPN_USER}}
        vpn_pass: ${{secrets.VPN_PASS}}
        sql_host: ${{vars.FD_LOGGER_HOST}}
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
        # TODO: set log_level to DEBUG once we've made sure there aren't excess outputs from the extractor itself.
        log_level: "INFO"
    - name: Set up Schema File
      uses: ./.github/actions/OGD_schema
      with:
        game: "PENGUINS"

  # 3. Perform export
    - name: Do Export of last week's data
      uses: ./.github/actions/export_last_week
      with:
        game: PENGUINS

  # 4. Cleanup & complete
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ./*.log
    - name: Upload zips as artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ./data/PENGUINS/*.zip
