name: "Export Previous Month of Data"
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'workflow_call' && 'Workflow Call' || 'Manual Run') }}
on:
  workflow_call:
    inputs:
      game:
        type: "string"
        description: "The game with data to export."
        required: true
        default: 'Crystal'
      python_version:
        type: "string"
        description: "Which version of Python to install on local GitHub Actions runner."
        required: false
        default: "3.12"
      upload_artifact:
        type: "boolean"
        description: "Whether to upload the file to GitHub as an artifact."
        required: false
        default: true

jobs:

  export_data:
    name: Export Game
    runs-on: ubuntu-22.04
    timeout-minutes: 1440

    steps:

    # 1. Local checkout & config
    - uses: actions/checkout@v4
    - name: Set up Google Cloud
      uses: ./.github/actions/gCloud_setup
      with:
        game: ${{ inputs.game }}
        ogd_id:  ${{ secrets.OGD_BQ_PROJECT_ID }}
        ogd_key: ${{ secrets.OGD_SELECTOR_BQ_KEY }}
        mashopolis_id:  ${{ secrets.BQ_MASHOPOLIS_PROJECT_ID }}
        mashopolis_key: ${{ secrets.BQ_MASHOPOLIS_JSON }}
        shadowspect_id:  ${{ secrets.BQ_SHADOWSPECT_PROJECT_ID }}
        shadowspect_key: ${{ secrets.BQ_SHADOWSPECT_JSON }}
        shipwrecks_id:  ${{ secrets.BQ_SHIPWRECKS_PROJECT_ID }}
        shipwrecks_key: ${{ secrets.BQ_SHIPWRECKS_JSON }}
    - name: Connect to VPN
      uses: opengamedata/actions-openconnect-vpn@v1.1
      with:
        username: ${{ secrets.VPN_USER }}
        password: ${{ secrets.VPN_PASS }}
        endpoint: "soe.vpn.wisc.edu"
    - name: Get Dependencies
      uses: opengamedata/actions-setup-ogd-py-dependencies@v1.1
      with:
        python_version: ${{ vars.OGD_PYTHON_VERSION }}
    - name: Set up Config File
      uses: ./.github/actions/OGD_config
      with:
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
        ssh_host: ${{vars.FD_STORE_HOST}}
        ssh_user: ${{secrets.VPN_USER}}
        ssh_pass: ${{secrets.VPN_PASS}}
        slice_size: ${{ github.event.inputs.slice_size }}
        log_level: ${{ github.event.inputs.log_level }}

    # 2. Execute process
    - name: Get export month
      run: |
        MONTH=$(date -d "$(date +%Y-%m-01) -1 month" +'%m')
        YEAR=$(date -d "$(date +%Y-%m-01) -1 month" +'%Y')
        MONTH_YEAR=$MONTH/$YEAR
        echo "MONTH_YEAR=" $MONTH_YEAR >> $GITHUB_ENV
        echo exporting $MONTH_YEAR
      shell: bash
    - name: Execute data export
      uses: ./.github/actions/export_custom_month
      with:
        game: ${{ inputs.game }}
        month_year: ${{ env.MONTH_YEAR }}
