# Workflow to run a test export of Crystal whenever we change the core OGD backend code.
# Chose Crystal simply because it has an extractor, but not a particularly complex one.
name: Varied Slice Sizes Test
on:
  workflow_dispatch: # Allow manual trigger of this workflow from the Actions tab

jobs:
  test_export:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        size: [1000, 100, 250, 500, 1000, 2000]
      fail-fast: false # we don't want to cancel just because one game fails.
      max-parallel: 1

    steps:
    - uses: actions/checkout@v2
    - name: Get OpenConnect
      run: sudo apt-get -q update && sudo apt-get -q install openconnect
    - name: Connect VPN
      run: echo ${{ secrets.VPN_PASS }} | sudo openconnect --protocol=gp -u ${{ secrets.VPN_USER }} --passwd-on-stdin soe.vpn.wisc.edu &
    - name: Get Dependencies
      uses: ./.github/actions/OGD_dependencies
    - name: Set up Config File
      uses: ./.github/actions/OGD_config
      with:
        vpn_user: ${{secrets.VPN_USER}}
        vpn_pass: ${{secrets.VPN_PASS}}
        sql_host: ${{secrets.SQL_HOST}}
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
        log_level: "INFO"
    - name: Attempt Export with slice size 100
      uses: ./.github/actions/export_last_month
      with:
        game: WAVES
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./*.log
